### ISSUE TITLE
Setup the skeleton for a Quarto book

### ISSUE THREAD

**Issue by joelostblom** [joelostblom/viz-oer#10]

**Comment by joelostblom** [comment]
@rorywhite200 I don't think I will be able to set this up, so could you could you get started on this? I think it will make sense for you to read through the quarto docs anyways to know how to use the callouts etc, so starting from scratch might be easier anyways then jumping into a setup I made. You can find the docs for how to get started here https://quarto.org/docs/books/. And if there is any confusion or you feel like it is a time sink, you can just prioritize creating the content for the first chapter in a regular MD file and I can help with the book setup when I'm back. A tip is that I usually use `quarto render` from the command line instead of their preview functionality, but you might want to try both and see what you prefer.

**Comment by rorywhite200** [comment]
> @rorywhite200 I don't think I will be able to set this up, so could you could you get started on this?

Sure I will give it a shot!
