### ISSUE TITLE
introducing the narrative of the book

### ISSUE THREAD

**Issue by rorywhite200** [joelostblom/viz-oer#15]
If we want to have an overarching theme / world building for our book I'm wondering how this fits with the first chapter. One idea is that we could introduce the world in the intro before that? 

I imagine we could either frame chapter 1 as essentially a survival guide / tutorial island before the missions start. Or we could dive straight into our world in the exercises in chapter 1. 

I'm thinking the latter might be better. For the initial scatterplots. I know you wanted to incorporate something diet related. It could be like a scatterplot of environmental impact per calorie vs amount eaten in our city.. something like that. You work for the Ministry for the Environment. 

The intro could frame the wider problem. And it would be cool to have a recurring motif where a new persona is introduced. If each scenario is based on a character in the city, then maybe their profile appears almost like an identity card.

**Comment by rorywhite200** [comment]
I've started with the latter approach for now. I've incorporated an ID card as I think this could be a recurring motif and clearly define which character you are, making it more engaging and game like

<img width="650" alt="Screenshot 2024-08-01 at 7 59 37 PM" src="https://github.com/user-attachments/assets/c9f97940-0dbb-4a4b-bd7c-02199b8e7277">

**Comment by rorywhite200** [comment]
OK I took it a bit further. I believe that for reasoning exercises you could justify your choices / ideas as the character. The way I did this was designing a chat interface between the character and their supervisor, in this case the Minister for Environment, powered by an LLM. I think this could be very engaging and get close to the vision of guiding the student to the solution without revealing it. It also helps with world building and makes the student feel like they are actually that character. This concept could be reused in multiple chapters.

**Comment by joelostblom** [comment]
We have introduced most of what is mentioned in this issue and the remaining narrative work is done in #35, so I'm closing this issue.
